#print("Hello world")
#print("hello".upper())
#print("HELLO".lower())
#print("hello".capitalize())
#print("hello" +    "world")
#print(type('hello'))
#print(dir("hello"))

#print(int("1"))
#print(int("1.1"))
#print(float("1.1"))
#print([1,2,3])
#print(list((1,2)))
#print((1,1,1))
#print(tuple([1,1,1]))
#print(set())
#print(set([1,'a',2,4,'f','s']))
#print(dict(x = 1, y = 2))
#print({'x' : 2, 'y' : 4 })
